# Generated by Django 5.0.3 on 2024-10-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_task_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
